DROP DATABASE burgers_db;

CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers (
  id INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (id),
  burger_name VARCHAR(300) NOT NULL,
  devoured BOOLEAN NOT NULL DEFAULT 0,
  date DATETIME DEFAULT CURRENT_TIMESTAMP
);
